use cape_codd;

-- SELECT DISTINCT BUYER, DEPARTMENT 
-- FROM SKU_DATA;

-- TOP 5
SELECT BUYER, DEPARTMENT 
FROM SKU_DATA LIMIT 5;

SELECT *
FROM SKU_DATA
WHERE BUYER = 'pete hansen' and DEPARTMENT = 'water sports';

SELECT *
FROM SKU_DATA
WHERE BUYER = 'pete hansen' and NOT DEPARTMENT = 'water sports';

SELECT *
FROM SKU_DATA
WHERE SKU_DESCRIPTION LIKE "%BLUE%";

-- SELECT *
-- FROM SKU_DATA
-- WHERE SKU_DATA IS NOT NULL;

SELECT *
FROM CATALOG_SKU_2017
WHERE DATEONWEBSITE = '2017-01-01';

SELECT*
FROM SKU_DATA
WHERE SKU > 200000;

SELECT SKU_DESCRIPTION, DEPARTMENT
FROM SKU_DATA
WHERE DEPARTMENT = 'CLIMBING';

SELECT SKU_DESCRIPTION, BUYER
FROM SKU_DATA
WHERE DEPARTMENT = 'CLIMBING';

-- IT ASCENDS BY DEFAULT
SELECT*
FROM ORDER_ITEM
ORDER BY ORDERNUMBER;

SELECT*
FROM ORDER_ITEM
ORDER BY  ORDERNUMBER ASC, PRICE DESC;

SELECT*
FROM SKU_DATA
WHERE BUYER IN ('Nancy meyers', 'cindy lo', 'jerry martin');

SELECT *
FROM ORDER_ITEM
WHERE EXTENDEDPRICE >= 100
AND EXTENDEDPRICE <= 200
ORDER BY EXTENDEDPRICE;

SELECT*
FROM ORDER_ITEM
WHERE EXTENDEDPRICE BETWEEN 100 AND 200 ORDER BY EXTENDEDPRICE




